#ifndef DECODESTATUS_H_
#define DECODESTATUS_H_

#define I0_TRANS_SUCCESS_NO_FURTHER_PROC	0x00
#define I0_DECODE_INVALID_INSTRUCTION		0x01
	#define I0_DECODE_OPR_I_MATTR_UNDEFINED 	0x01
	#define I0_DECODE_OPR_I_MATTR_NOTIMPLEMENT	0x02
	#define I0_DECODE_OPR_M_ADDRM_UNDEFINED		0x03
	#define I0_DECODE_OPR_M_ADDRM_EXCEPTION		0x04
	#define I0_DECODE_OPCODE_UNDEFINED			0x05
	#define I0_DECODE_OPCODE_B_UNDEFINED		0x06
	#define I0_DECODE_OPERAND_UNDEFINED			0x07
#define I0_DECODE_SEGMENT_LIMIT				0x03
#define TRANS_NATIVE_CODE_SEGMENT_LIMIT		0x04
#define I0_DECODE_BRANCH					0x05
	#define I0_DECODE_JCC						0x01
	#define I0_DECODE_JMP						0x02
	#define I0_DECODE_JMP_INDIR					0x03
	#define I0_DECODE_EXIT						0x04
	#define I0_DECODE_INT						0x05

#endif /* DECODESTATUS_H_ */
